import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { FC, ReactNode } from "react";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Image Gallery",
  description: "Generated by Hablu Programmer!",
};

type TChildren = { children: ReactNode };
const RootLayout: FC<Readonly<TChildren>> = ({ children }) => (
  <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      {children}
    </body>
  </html>
);

export default RootLayout;
